export const ServicesGridData = [
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '1',
    references: 'Ladies Wash+Cut+Dry S1',
    category: '(01) Ladies Hair Cut',
    duration: 60,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '2',
    references: 'Ladies Wash+Cut+Dry S2',
    category: '(01) Ladies Hair Cut',
    duration: 50,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.1,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '3',
    references: 'Ladies Wash+Cut+Dry S3',
    category: '(01) Ladies Hair Cut',
    duration: 45,
    isShowOnline: true,
    isConsultation: false,
    price: 65,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '4',
    references: 'Mens Wash+Cut+Dry S1',
    category: '(02) Mens Hair Cut',
    duration: 45,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '5',
    references: 'Mens Wash+Cut+Dry S2',
    category: '(02) Mens Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 40,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '6',
    references: 'Mens Wash+Cut+Dry S3',
    category: '(02) Mens Hair Cut',
    duration: 35,
    isShowOnline: true,
    isConsultation: false,
    price: 45,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '7',
    references: 'Mens Wash+Cut+Dry S4',
    category: '(02) Mens Hair Cut',
    duration: 35,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.15,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '8',
    references: 'Girls Wash+Cut+Dry',
    category: '(03) Kids Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.2,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '9',
    references: 'Boys Wash+Cut+Dry',
    category: '(03) Kids Hair Cut',
    duration: 25,
    isShowOnline: true,
    isConsultation: false,
    price: 25,
    discount: 0.2,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '10',
    references: 'Girl Student Wash+Cut',
    category: '(04) Students Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.2,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '11',
    references: 'Boy Student Wash+Cut',
    category: '(04) Students Hair Cut',
    duration: 25,
    isShowOnline: true,
    isConsultation: false,
    price: 30,
    discount: 0.2,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '12',
    references: 'Highlights 1/1 S3',
    category: '(05) Colouring',
    duration: 90,
    isShowOnline: true,
    isConsultation: true,
    price: 95,
    discount: 0.25,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '13',
    references: 'Highlights 1/1 S4',
    category: '(05) Colouring',
    duration: 90,
    isShowOnline: true,
    isConsultation: true,
    price: 105,
    discount: 0.25,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '14',
    references: 'Highlights 1/2 S3',
    category: '(05) Colouring',
    duration: 75,
    isShowOnline: true,
    isConsultation: true,
    price: 75,
    discount: 0.25,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    offeringId: '15',
    references: 'Highlights 1/2 S4',
    category: '(05) Colouring',
    duration: 75,
    isShowOnline: true,
    isConsultation: true,
    price: 85,
    discount: 0.25,
  },
];
