enum OfferIcons {
  Tooth = 'Tooth',
}

interface Offer {
  offerID: number;
  offerIconName: OfferIcons;
  references: string;
  detailsReference: string;
  category: string;
  duration: number;
  isShowOnline: boolean;
  isConsultation: boolean;
  price: number;
  discount: number;
}

export const ServicesGridData: Offer[] = [
  {
    offerID: 1,
    offerIconName: OfferIcons.Tooth,
    references: 'Ladies Wash+Cut+Dry S1',
    detailsReference: 'Details reference',
    category: '(01) Ladies Hair Cut',
    duration: 60,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.15,
  },
  {
    offerID: 2,
    offerIconName: OfferIcons.Tooth,
    references: 'Ladies Wash+Cut+Dry S2',
    detailsReference: 'Details reference',
    category: '(01) Ladies Hair Cut',
    duration: 50,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.1,
  },
  {
    offerID: 3,
    offerIconName: OfferIcons.Tooth,
    references: 'Ladies Wash+Cut+Dry S3',
    detailsReference: 'Details reference',
    category: '(01) Ladies Hair Cut',
    duration: 45,
    isShowOnline: true,
    isConsultation: false,
    price: 65,
    discount: 0.15,
  },
  {
    offerID: 4,
    offerIconName: OfferIcons.Tooth,
    references: 'Mens Wash+Cut+Dry S1',
    detailsReference: 'Details reference',
    category: '(02) Mens Hair Cut',
    duration: 45,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.15,
  },
  {
    offerID: 5,
    offerIconName: OfferIcons.Tooth,
    references: 'Mens Wash+Cut+Dry S2',
    detailsReference: 'Details reference',
    category: '(02) Mens Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 40,
    discount: 0.15,
  },
  {
    offerID: 6,
    offerIconName: OfferIcons.Tooth,
    references: 'Mens Wash+Cut+Dry S3',
    detailsReference: 'Details reference',
    category: '(02) Mens Hair Cut',
    duration: 35,
    isShowOnline: true,
    isConsultation: false,
    price: 45,
    discount: 0.15,
  },
  {
    offerID: 7,
    offerIconName: OfferIcons.Tooth,
    references: 'Mens Wash+Cut+Dry S4',
    detailsReference: 'Details reference',
    category: '(02) Mens Hair Cut',
    duration: 35,
    isShowOnline: true,
    isConsultation: false,
    price: 55,
    discount: 0.15,
  },
  {
    offerID: 8,
    offerIconName: OfferIcons.Tooth,
    references: 'Girls Wash+Cut+Dry',
    detailsReference: 'Details reference',
    category: '(03) Kids Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.2,
  },
  {
    offerID: 9,
    offerIconName: OfferIcons.Tooth,
    references: 'Boys Wash+Cut+Dry',
    detailsReference: 'Details reference',
    category: '(03) Kids Hair Cut',
    duration: 25,
    isShowOnline: true,
    isConsultation: false,
    price: 25,
    discount: 0.2,
  },
  {
    offerID: 10,
    offerIconName: OfferIcons.Tooth,
    references: 'Girl Student Wash+Cut',
    detailsReference: 'Details reference',
    category: '(04) Students Hair Cut',
    duration: 40,
    isShowOnline: true,
    isConsultation: false,
    price: 35,
    discount: 0.2,
  },
  {
    offerID: 11,
    offerIconName: OfferIcons.Tooth,
    references: 'Boy Student Wash+Cut',
    detailsReference: 'Details reference',
    category: '(04) Students Hair Cut',
    duration: 25,
    isShowOnline: true,
    isConsultation: false,
    price: 30,
    discount: 0.2,
  },
  {
    offerID: 12,
    offerIconName: OfferIcons.Tooth,
    references: 'Highlights 1/1 S3',
    detailsReference: 'Details reference',
    category: '(05) Colouring',
    duration: 90,
    isShowOnline: true,
    isConsultation: true,
    price: 95,
    discount: 0.25,
  },
  {
    offerID: 13,
    offerIconName: OfferIcons.Tooth,
    references: 'Highlights 1/1 S4',
    detailsReference: 'Details reference',
    category: '(05) Colouring',
    duration: 90,
    isShowOnline: true,
    isConsultation: true,
    price: 105,
    discount: 0.25,
  },
  {
    offerID: 14,
    offerIconName: OfferIcons.Tooth,
    references: 'Highlights 1/2 S3',
    detailsReference: 'Details reference',
    category: '(05) Colouring',
    duration: 75,
    isShowOnline: true,
    isConsultation: true,
    price: 75,
    discount: 0.25,
  },
  {
    offerID: 15,
    offerIconName: OfferIcons.Tooth,
    references: 'Highlights 1/2 S4',
    detailsReference: 'Details reference',
    category: '(05) Colouring',
    duration: 75,
    isShowOnline: true,
    isConsultation: true,
    price: 85,
    discount: 0.25,
  },
];
