import AbrahamCorinne from '../_assets/customers/StyCal-Customer-Photo-S1 (14).jpg';
import AbrahamOliver from '../_assets/customers/StyCal-Customer-Photo-S1 (1).jpg';
import Ilona from '../_assets/customers/StyCal-Customer-Photo-S1 (12).jpg';
import Tom from '../_assets/customers/StyCal-Customer-Photo-S1 (13).jpg';
import Elizabete from '../_assets/customers/StyCal-Customer-Photo-S1 (2).jpg';
import Cindia from '../_assets/customers/StyCal-Customer-Photo-S1 (16).jpg';
import { CustomersDataItem } from './CustomersTypes';

export const CustomersGridData: CustomersDataItem[] = [
  {
    ID: Math.random() * Math.random(),
    teamID: '1269',
    lastName: 'Smith',
    firstName: 'Jon',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: '',
    mobilePhone: '',
    lastUpdate: new Date(),
    photo: '',
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '1270',
    lastName: 'Maldini',
    firstName: 'Paulo',
    gender: 'Male' as const,
    svcStaff: '',
    upcoming: '',
    email: '',
    mobilePhone: '',
    lastUpdate: new Date(),
    photo: '',
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '54',
    lastName: 'Abraham',
    firstName: 'Corinne',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'Coralie.Abraham@scheduling',
    mobilePhone: '+111897654324570',
    lastUpdate: new Date(),
    photo: AbrahamCorinne,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '290',
    lastName: 'Abraham',
    firstName: 'Oliver',
    gender: 'Male' as const,
    svcStaff: '',
    upcoming: '',
    email: 'Oliver.Abraham@scheduling',
    mobilePhone: '+11189765898988',
    lastUpdate: new Date(),
    photo: AbrahamOliver,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '77',
    lastName: 'Acciardi',
    firstName: 'Ilona',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'ilond.acciardi@scheduling',
    mobilePhone: '+11189765898988',
    lastUpdate: new Date(),
    photo: Ilona,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '200',
    lastName: 'Acciardi',
    firstName: 'Tom',
    gender: 'Male' as const,
    svcStaff: '',
    upcoming: '',
    email: 'tom.acciardi@scheduling',
    mobilePhone: '+11189765897988',
    lastUpdate: new Date(),
    photo: Tom,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '1142',
    lastName: 'Adame',
    firstName: 'TJ',
    gender: 'Male' as const,
    svcStaff: '',
    upcoming: '',
    email: 'tj.adame@scheduling',
    mobilePhone: '+18989765897988',
    lastUpdate: new Date(),
    photo: '',
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '1268',
    lastName: 'Adame',
    firstName: 'Elizabete',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'elizabete.adame@scheduling',
    mobilePhone: '+18989765897988',
    lastUpdate: new Date(),
    photo: Elizabete,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '201',
    lastName: 'Adamson',
    firstName: 'Tatiana',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'tatiana.adamson@scheduling',
    mobilePhone: '+18989765897633',
    lastUpdate: new Date(),
    photo: '',
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '476',
    lastName: 'Adamson',
    firstName: 'Cindia',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'Cindia.adamson@scheduling',
    mobilePhone: '+1189796168185',
    lastUpdate: new Date(),
    photo: Cindia,
  },
  {
    ID: Math.random() * Math.random(),
    teamID: '477',
    lastName: 'Pye',
    firstName: 'Stephen',
    gender: 'Female' as const,
    svcStaff: '',
    upcoming: '',
    email: 'Cindia.adamson@scheduling',
    mobilePhone: '+1189796168185',
    lastUpdate: new Date(),
    photo: Cindia,
  },
];
