export const homeGridData = [
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0635',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Romanova',
    services: '02-Mens Wash+Cut+Dry S3_006',
    budget: 38.25,
    lastName: 'Pye',
    firstName: 'Stephen',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 635,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'C.Wong-0499',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Khan',
    services: '05-Highlights 1/2 S3_014',
    budget: 56.25,
    lastName: 'Wong',
    firstName: 'Lee',
    phone: '+189762823877',
    lastUpdate: new Date().toISOString(),
    eventId: 499,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0500',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Robinson',
    services: '04-Boy Student Wash+Cut_011',
    budget: 24,
    lastName: 'Pye',
    firstName: 'Stephen',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 500,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0501',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Wenger',
    services: '02-Mens Wash+Cut+Dry S2_005 | 04-Boy Student Wash+Cut_011',
    budget: 58,
    lastName: 'Pye',
    firstName: 'Stephen',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 501,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0502',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Giround',
    services: '02-Mens Wash+Cut+Dry S2_005 | 05-Highlights T-Section S3_016',
    budget: 99.25,
    lastName: 'Pye',
    firstName: 'Stephen',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 502,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'C.A.Female-0640',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Wenger',
    services: '08-Balayage Natural S4_027',
    budget: 110.25,
    lastName: 'A.Female',
    firstName: 'Consultation',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 640,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0503',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Khan',
    services: '08-Balayage Natural S4_027',
    budget: 48,
    lastName: 'A.Female',
    firstName: 'Consultation',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 503,
  },
  {
    id: (Math.random() * Math.random()).toString(),
    clock: '',
    status: '(2) Pending',
    references: 'S.Pye-0504',
    start: new Date().toISOString(),
    end: new Date().toISOString(),
    svcStaff: 'Robinson',
    services: '06-Ladies Blow Dry S1_021',
    budget: 15.49,
    lastName: 'A.Female',
    firstName: 'Consultation',
    phone: '0798302214',
    lastUpdate: new Date().toISOString(),
    eventId: 504,
  },
];
