// Types
import { AgendaDataItem, StatusNames } from './AgendaTypes';

const now = Date.now();
const hour = 3.6e6;

export const AgendaGridData: AgendaDataItem[] = [
  {
    id: 1,
    status: StatusNames.Pending,
    references: 'S.Pye-0635',
    start: now,
    end: now + hour,
    svcStaff: 'Romanova',
    services: 'Boy Student Wash+Cut',
    totalPrice: 38.25,
    lastName: 'Pye',
    firstName: 'Stephen',
    fullName: 'Stephen Pye',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 635,
    customerGender: 'Male',
  },
  {
    id: 2,
    status: StatusNames.Booked,
    references: 'C.Wong-0499',
    start: now,
    end: now + hour,
    svcStaff: 'Khan',
    services: 'Highlights 1/1 S3',
    totalPrice: 56.25,
    lastName: 'Wong',
    firstName: 'Lee',
    fullName: 'Lee Wong',
    phone: '+189762823877',
    lastUpdate: new Date(),
    eventId: 499,
    customerGender: 'Male',
  },
  {
    id: 3,
    status: StatusNames.Cancelled,
    references: 'S.Pye-0500',
    start: now,
    end: now + hour,
    svcStaff: 'Robinson',
    services: 'Highlights 1/1 S4',
    totalPrice: 24,
    lastName: 'Pye',
    firstName: 'Stephen',
    fullName: 'Stephen Pye',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 500,
    customerGender: 'Male',
  },
  {
    id: 4,
    status: StatusNames.Checking,
    references: 'S.Pye-0501',
    start: now,
    end: now + hour,
    svcStaff: 'Wenger',
    services: 'Highlights 1/2 S3',
    totalPrice: 58,
    lastName: 'Pye',
    firstName: 'Stephen',
    fullName: 'Stephen Pye',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 501,
    customerGender: 'Male',
  },
  {
    id: 5,
    status: StatusNames.Closed,
    references: 'S.Pye-0502',
    start: now,
    end: now + hour,
    svcStaff: 'Giround',
    services: 'Highlights 1/2 S4',
    totalPrice: 99.25,
    lastName: 'Pye',
    firstName: 'Stephen',
    fullName: 'Stephen Pye',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 502,
    customerGender: 'Male',
  },
  {
    id: 6,
    status: StatusNames.Consultation,
    references: 'C.A.Female-0640',
    start: now,
    end: now + hour,
    svcStaff: 'Wenger',
    services: 'Ladies Wash+Cut+Dry S1',
    totalPrice: 110.25,
    lastName: 'Adamson',
    firstName: 'Cindia',
    fullName: 'Cindia Adamson',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 640,
    customerGender: 'Female',
  },
  {
    id: 7,
    status: StatusNames.Other,
    references: 'S.Pye-0503',
    start: now,
    end: now + hour,
    svcStaff: 'Khan',
    services: 'Ladies Wash+Cut+Dry S2',
    totalPrice: 48,
    lastName: 'Adamson',
    firstName: 'Tatiana',
    fullName: 'Tatiana Adamson',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 503,
    customerGender: 'Female',
  },
  {
    id: 8,
    status: StatusNames.Paid,
    references: 'S.Pye-0504',
    start: now,
    end: now + hour,
    svcStaff: 'Robinson',
    services: 'Ladies Wash+Cut+Dry S3',
    totalPrice: 15.49,
    lastName: 'Abraham',
    firstName: 'Corinne',
    fullName: 'Corinne Abraham',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 504,
    customerGender: 'Female',
  },
  {
    id: 9,
    status: StatusNames.Reserved,
    references: 'S.Pye-0504',
    start: now,
    end: now + hour,
    svcStaff: 'Robinson',
    services: 'Mens Wash+Cut+Dry S1',
    totalPrice: 15.49,
    lastName: 'Acciardi',
    firstName: 'Ilona',
    fullName: 'Ilona Acciardi',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 505,
    customerGender: 'Female',
  },
  {
    id: 10,
    status: StatusNames.Unavailable,
    references: 'S.Pye-0504',
    start: now,
    end: now + hour,
    svcStaff: 'Robinson',
    services: 'Mens Wash+Cut+Dry S2',
    totalPrice: 15.49,
    lastName: 'Adame',
    firstName: 'Elizabete',
    fullName: 'Elizabete Adame',
    phone: '0798302214',
    lastUpdate: new Date(),
    eventId: 506,
    customerGender: 'Female',
  },
];
